version: "3.7"

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chat
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

volumes:
  db_data: {}